blueprints/artists.py
from flask import Blueprint, current_app, render_template, request, make_response
from common.auth import check_token
from common.artist import Artist
from common.db import get_db_connection
import mimetypes

bp = Blueprint("artists", __name__, url_prefix="/artists")


@bp.route("/")
@check_token(current_app)
def list(login_artist: Artist | None):
    conn = get_db_connection()
    artists = conn.execute("SELECT username FROM artists").fetchall()
    conn.close()
    return render_template("artists.jinja", artists=artists, login_artist=login_artist)


@bp.route("/<string:artist>")
@check_token(current_app)
def artist(login_artist, artist):
    conn = get_db_connection()
    page = request.args.get("page", type=int)
    if page is None:
        page = 0
    else:
        page -= 1
    offset = page * 50
    artist_id = conn.execute(
        "SELECT id FROM artists WHERE username = ?", (artist,)
    ).fetchone()
    comics = conn.execute(
        "SELECT * FROM comics WHERE artistid = ? ORDER BY created DESC LIMIT 51 OFFSET ?",
        (artist_id[0], offset),
    ).fetchall()
    series_db = conn.execute("SELECT id, name FROM series").fetchall()
    seriesdict = {}
    # convert the series to a dict for easy searching
    for series in series_db:
        seriesdict.update({series[0]: series[1]})
    conn.close()
    # if there are more comics, allow going to the next page
    # and clean up the extra comic
    if len(comics) > 50:
        comics.pop()
        allownext = True
    else:
        # if not, do not allow going to the next page
        allownext = False
    return render_template(
        "artist.jinja",
        artist=artist,
        comics=comics,
        page=page + 1,
        allownext=allownext,
        series=seriesdict,
        login_artist=login_artist,
    )


@bp.route("/<string:artist>/feed")
def feed(artist):
    conn = get_db_connection()
    artist_id = conn.execute(
        "SELECT id FROM artists WHERE username = ?", (artist,)
    ).fetchone()
    comics = conn.execute(
        "SELECT * FROM comics WHERE artistid = ? ORDER BY created DESC",
        (artist_id[0],),
    ).fetchall()
    series_db = conn.execute("SELECT id, name FROM series").fetchall()
    seriesdict = {}
    # convert the series to a dict for easy searching
    for series in series_db:
        seriesdict.update({series[0]: series[1]})
    artists = conn.execute("SELECT id, username FROM artists").fetchall()
    # convert the artist to a dict for easy searching
    artistdict = {}
    for other_artist in artists:
        artistdict.update({other_artist[0]: other_artist[1]})
    conn.close()
    response = make_response(
        render_template(
            "rss/artist.jinja",
            artist=artist,
            comics=comics,
            series=seriesdict,
            artists=artistdict,
            types_map=mimetypes.types_map,
        )
    )
    response.headers["Content-Type"] = "application/xml"
    return response

blueprints/auth.py
import jwt
from flask import (
    Blueprint,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from common.auth import check_token
from common.artist import Artist
from common.db import get_db_connection
from datetime import datetime, timedelta
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/testauth")
@check_token(current_app, required=True)
def testauth(artist):
    return f"artist: {artist[2]}"


@bp.route("/create_account", methods=("GET", "POST"))
@check_token(current_app)
def create_account(login_artist: Artist):
    if request.method == "POST":
        code = request.form["code"]
        try:
            request.form["ToS"]
        except:
            flash("You must agree to the Terms of Service!")
            return render_template("create_account.jinja", login_artist=login_artist)
        if not code:
            flash("You need an invite code to join!")
        else:
            conn = get_db_connection()
            expired = conn.execute(
                "SELECT expired FROM codes WHERE code = ?", (request.form["code"],)
            ).fetchone()[0]
            if expired == False:
                passhash = generate_password_hash(request.form["password"])
                conn.execute(
                    "INSERT INTO artists (username, passhash, isadmin) VALUES (?, ?, ?)",
                    (request.form["username"], passhash, False),
                )
                conn.execute(
                    "UPDATE codes SET expired = ? WHERE code = ?", (True, code)
                )
            else:
                flash("Invalid code")
                return redirect(url_for("index"))
            conn.commit()
            conn.close()
            flash("Account created!")
            resp = make_response(redirect(url_for("index")))
            resp.set_cookie("token", "")
            return resp

    return render_template("create_account.jinja", login_artist=login_artist)


@bp.route("/login", methods=["GET", "POST"])
@check_token(current_app)
def login(login_artist: Artist | None):
    if request.method == "GET":
        return render_template("login.jinja", login_artist=login_artist)
    # try to login:
    conn = get_db_connection()
    artist = conn.execute(
        "SELECT passhash, id FROM artists WHERE username = ?",
        (request.form["username"],),
    ).fetchone()

    if artist is None:
        flash("Invalid username or password!")
        return redirect("login")
    if check_password_hash(artist[0], request.form["password"]) == False:
        flash("Invalid username or password!")
        return redirect("login")

    # if we made it this far, the username and password is valid!
    token = jwt.encode(
        {
            "id": artist[1],
            "exp": datetime.utcnow()
            + timedelta(seconds=current_app.config["MAX_LOGIN_TIME"]),
        },
        current_app.config["SECRET_KEY"],
    )
    resp = make_response(redirect(url_for("index")))
    resp.set_cookie(
        "token",
        token,
        max_age=current_app.config["MAX_LOGIN_TIME"],
        secure=True,
        httponly=True,
        samesite="Strict",
    )
    return resp


@bp.route("/logout")
def logout():
    flash("Logged out, this did not invalidate your token!")
    flash(
        "This means, if you were infected by malware, you'll need to contact AnnoyingRains!"
    )
    resp = make_response(redirect(url_for("index")))
    resp.set_cookie("token", "")
    return resp

blueprints/comics.py
import os
from flask import (
    Blueprint,
    current_app,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from common.auth import check_token
from common.artist import Artist
from common.db import get_db_connection
from common.db import get_comic

bp = Blueprint("comics", __name__, url_prefix="/comics")


@bp.route("/<int:comic_id>")
@check_token(current_app)
def comic(login_artist: Artist, comic_id):
    comic = get_comic(comic_id)
    conn = get_db_connection()
    artist = conn.execute(
        "SELECT username FROM artists WHERE id = ?", (comic[4],)
    ).fetchone()
    if comic["seriesid"]:
        series = conn.execute(
            "SELECT name FROM series WHERE id = ?", (comic["seriesid"],)
        ).fetchone()[0]
    else:
        series = None

    # find the next comic ID depending on the previous page
    if request.args.get("via", default=None) is not None:
        referrer = request.args.get("via")
    else:
        if request.referrer:
            referrer = request.referrer.split("/")[3]
        else:
            referrer = None
    match referrer:
        case "series":
            nextcomic = conn.execute(
                "SELECT id FROM comics WHERE seriesid = ? AND id > ? LIMIT 1",
                (comic["seriesid"], comic["id"]),
            ).fetchone()
            previouscomic = conn.execute(
                "SELECT id FROM comics WHERE seriesid = ? AND id < ? ORDER BY id DESC LIMIT 1",
                (comic["seriesid"], comic["id"]),
            ).fetchone()
        case "artists":
            nextcomic = conn.execute(
                "SELECT id FROM comics WHERE artistid = ? AND id > ? LIMIT 1",
                (comic["artistid"], comic["id"]),
            ).fetchone()
            previouscomic = conn.execute(
                "SELECT id FROM comics WHERE artistid = ? AND id < ? ORDER BY id DESC LIMIT 1",
                (comic["artistid"], comic["id"]),
            ).fetchone()
        case _ if referrer is not None and (
            referrer.startswith("?") or referrer == "index" or referrer == ""
        ):
            nextcomic = conn.execute(
                "SELECT id FROM comics WHERE id > ? LIMIT 1",
                (comic["id"],),
            ).fetchone()
            previouscomic = conn.execute(
                "SELECT id FROM comics WHERE id < ? ORDER BY id DESC LIMIT 1",
                (comic["id"],),
            ).fetchone()
            referrer = "index"
        case _:
            nextcomic = None
            previouscomic = None

    if nextcomic is not None:
        nextcomic = nextcomic[0]

    if previouscomic is not None:
        previouscomic = previouscomic[0]

    return render_template(
        "comic.jinja",
        comic=comic,
        artist=artist[0],
        series=series,
        nextcomic=nextcomic,
        previouscomic=previouscomic,
        referrer=referrer,
        login_artist=login_artist,
    )


@bp.route("/<int:id>/edit", methods=("GET", "POST"))
@check_token(current_app, required=True)
def edit(login_artist: Artist, id):
    comic = get_comic(id)
    if request.method == "POST":
        title = request.form["title"]
        if not title:
            flash("Title is required!")
        else:
            conn = get_db_connection()
            artistid = conn.execute(
                "SELECT artistid FROM comics WHERE id = ?", (id,)
            ).fetchone()[0]
            if login_artist.id == artistid or login_artist.isadmin:
                # all checks passed, update the database
                if request.form["series"] != "None":
                    seriesid = conn.execute(
                        "SELECT id FROM series WHERE name = ?",
                        (request.form["series"],),
                    ).fetchone()[0]
                    conn.execute(
                        "UPDATE comics SET (title, seriesid) = (?, ?)" " WHERE id = ?",
                        (title, seriesid, id),
                    )
                else:
                    # this comic is not in a series
                    conn.execute(
                        "UPDATE comics SET (title, seriesid) = (?, ?)" " WHERE id = ?",
                        (title, None, id),
                    )
            else:
                flash("You can't edit other people's comics!")
            conn.commit()
            conn.close()
            return redirect(url_for("index"))
    conn = get_db_connection()
    series = conn.execute("SELECT name FROM series").fetchall()
    conn.commit()
    conn.close()
    return render_template(
        "edit.jinja", comic=comic, series=series, login_artist=login_artist
    )


@bp.route("/<int:id>/delete", methods=("POST",))
@check_token(current_app, required=True)
def delete(login_artist: Artist, id):
    comic = get_comic(id)
    conn = get_db_connection()
    artistid = conn.execute(
        "SELECT artistid FROM comics WHERE id = ?", (id,)
    ).fetchone()[0]
    if login_artist.id == artistid or login_artist.isadmin:
        fileext = conn.execute(
            "SELECT fileext FROM comics WHERE id = ?", (id,)
        ).fetchone()[0]
        os.remove(f"static/comics/{id}.{fileext}")
        conn.execute("DELETE FROM comics WHERE id = ?", (id,))
    else:
        flash("You can't delete other people's comics!")
        return redirect(url_for("index"))
    conn.commit()
    conn.close()
    flash('"{}" was successfully deleted!'.format(comic["title"]))
    return redirect(url_for("index"))

blueprints/create.py
import os
import requests
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from common.auth import check_token
from common.artist import Artist
from common.db import get_db_connection
from werkzeug.utils import secure_filename

bp = Blueprint("create", __name__, url_prefix="/create")


def allowed_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower()
        in current_app.config["ALLOWED_EXTENSIONS"]
    )


@bp.route("/comic", methods=("GET", "POST"))
@check_token(current_app, required=True)
def comic(login_artist: Artist):
    if request.method == "POST":
        conn = get_db_connection()
        title = request.form["title"]
        # check if the post request has the file part
        if "image" not in request.files:
            flash("No file part")
            return redirect(request.url)
        file = request.files["image"]
        # check to see if an empty file part is uploaded
        # as some browsers upload an empty file part when none is selected
        if file.filename == "":
            flash("No selected file")
            return redirect(request.url)

        if file and allowed_file(file.filename):
            if not title:
                flash("Title is required!")
                return redirect(request.url)
            else:
                cur = conn.cursor()
                artistid = cur.execute(
                    "SELECT artistid FROM series WHERE name = ?",
                    (request.form["series"],),
                ).fetchone()
                try:
                    artistid = artistid[0]
                except:
                    artistid = None
                # if artistid is None, allow anyone to post to the series
                if login_artist.id != artistid and artistid is not None:
                    flash("You cannot add your comic to someone else's series!")
                    return redirect(url_for("create.comic"))
                # actually add to the database
                if artistid is not None:
                    seriesid = cur.execute(
                        "SELECT id FROM series WHERE name = ?",
                        (request.form["series"],),
                    ).fetchone()[0]
                else:
                    seriesid = None
                cur.execute(
                    "INSERT INTO comics (title, fileext, artistid, seriesid) VALUES (?, ?, ?, ?)",
                    (title, secure_filename(file.filename.split(".")[-1]), login_artist.id, seriesid),  # type: ignore
                )
                conn.commit()
                filename = f"{cur.lastrowid}.{secure_filename(file.filename.split('.')[-1])}"  # type: ignore
                file.save(os.path.join(current_app.config["UPLOAD_FOLDER"], filename))
                cur.close()
                conn.close()
                webhookURL = os.getenv("DISCORD_WEBHOOK_URL")
                print(webhookURL)
                if webhookURL is not None:
                    requests.post(
                        webhookURL,
                        json={
                            "username": login_artist.username,
                            "embeds": [
                                {
                                    "title": title,
                                    "url": f"{current_app.config['SERVER_ADDRESS']}/{cur.lastrowid}",
                                    "description": "Uploaded a new comic",
                                    "image": {
                                        "url": f"{current_app.config['SERVER_ADDRESS']}/static/comics/{filename}"
                                    },
                                }
                            ],
                        },
                    )
                return redirect(url_for("index"))
        else:
            flash(
                "You either did not attach a file, or the file extension was not allowed."
            )
            return redirect(request.url)
    else:
        conn = get_db_connection()
        series = conn.execute("SELECT name FROM series").fetchall()
        conn.commit()
        conn.close()
        return render_template("create.jinja", series=series, login_artist=login_artist)


@bp.route("/series", methods=("GET", "POST"))
@check_token(current_app)
def series(login_artist: Artist):
    if request.method == "POST":
        conn = get_db_connection()
        test = conn.execute(
            "SELECT name FROM series WHERE name = ?", (request.form["name"],)
        ).fetchone()
        if test is not None:
            # there is already a series with this name
            flash("There is already a series with this name!")
            return redirect("/create_series")
        conn.execute(
            "INSERT INTO series (name, artistid) VALUES (?, ?)",
            (request.form["name"], login_artist.id),
        )
        conn.commit()
        conn.close()
        flash("Series created! You can now publish comics to it!")
        return redirect("/")
    else:
        return render_template("create_series.jinja", login_artist=login_artist)

templates/admin_panel.jinja
{% extends 'base.jinja' %}
{% from 'macros/sticky.jinja' import sticky %}
{% from 'macros/notepad.jinja' import notepad %}

{% block content %}
{{ notepad("Admin Panel") }}
<div class="notecontainer">
    {% call sticky("Create a new signup code", none) %}
    <form action="/admin/create_signup_code" method="post">
        <input type="text" name="code" placeholder="code">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endcall %}
    {% call sticky("Add a new artist", none) %}
    <form action="/admin/create_artist" method="post">
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <br>
        <label for="isadmin">Make them an admin?</label>
        <input type="checkbox" name="isadmin">
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endcall %}
    {% call sticky("Lock artist's account", none) %}
    <h3></h3>
    <form action="/admin/lock_artist" method="post">
        <input type="text" name="username" placeholder="Username">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endcall %}
    {% call sticky("Unlock artist's account", none) %}
    <form action="/admin/unlock_artist" method="post">
        <input type="text" name="username" placeholder="Username">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endcall %}
    {% call sticky("Delete artist", none)%}
    <form action="/admin/delete_artist" method="post">
        <input type="text" name="username" placeholder="Username">
        <button type="submit" class="btn btn-primary"
            onclick="return confirm('Are you sure you want to DELETE this user?')">Submit</button>
    </form>
    {% endcall %}
    <!-- This fake element is only here to ensure that the final sticky isn't forced to be an extra row down -->
    <div style="visibility:hidden; height:0px; width: 20em"></div>
</div>
{% endblock %}

templates/artist.jinja
{% extends 'base.jinja' %}
{% from 'macros/sticky.jinja' import sticky %}
{% from 'macros/notepad.jinja' import notepad %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="All of ComicWorld!" href="/feed" />
<link rel="alternate" type="application/rss+xml" title="{{artist}}'s feed" href="{{artist}}/feed" />
{% endblock %}

{% block content %}
{{ notepad(artist + "'s page", true, page, allownext) }}
<div class="notecontainer">
    {% for comic in comics %}
    {% call sticky(comic['title'], url_for('comics.comic', comic_id=comic['id']), editable=true) %}
    {% if comic['seriesid'] %}
    <span class="badge badge-primary">From series: <a
            href="/series/{{series[comic['seriesid']]}}">{{series[comic['seriesid']] }}</a></span>
    <br>
    {% endif %}
    <span class="badge badge-primary">{{ comic['created'] }}</span>
    <a href="{{ url_for('comics.comic', comic_id=comic['id']) }}">
        <img src="/static/comics/{{ comic['id'] }}.{{ comic['fileext'] }}">
    </a>
    {% endcall %}
    {% endfor %}
    <!-- This fake element is only here to ensure that the final sticky isn't forced to be an extra row down -->
    <div style="visibility:hidden; height:0px; width: 20em"></div>
</div>

<div class="linkbar">
    {% if page - 1 > 0 %} <a href="?page={{page - 1}}">Previous Page</a>{% endif %}{% if page - 1 > 0 and allownext%} |
    {% endif %}{% if allownext %}<a href="?page={{page + 1}}">Next Page</a> {% endif %}
</div>
{% endblock %}

templates/artists.jinja
{% extends 'base.jinja' %}
{% from 'macros/sticky.jinja' import sticky %}
{% from 'macros/notepad.jinja' import notepad %}

{% block content %}
{{ notepad("Artists:") }}

<div class="notecontainer">
    {% for artist in artists %}
    {% call sticky(artist[0], url_for('artists.artist', artist=artist[0])) %}
    {% endcall %}
    {% endfor %}
    <!-- This fake element is only here to ensure that the final sticky isn't forced to be an extra row down -->
    <div style="visibility:hidden; height:0px; width: 20em"></div>
</div>
{% endblock %}

templates/base.jinja
<!doctype html>
<html lang="en" {% if request.cookies['darkmode'] %} class="dark" {% endif %}>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="/static/css/main.css">
  {% if request.cookies['darkmode'] %}
  <link rel="stylesheet" href="/static/css/colours-dark.css">
  {% else %}
  <link rel="stylesheet" href="/static/css/colours.css">
  {% endif %}
  {% block extrahead %}{% endblock %}
</head>

<body>
  <div class="linkbar">
    <a class="navbar-brand" href="{{ url_for('index')}}">ComicWorld</a> |
    <a class="nav-link" href="{{url_for('artists.list')}}">Artists</a> |
    <a class="nav-link" href="{{url_for('series.list')}}">Series</a> |
    <a class="nav-link" href="{{url_for('rss')}}">RSS</a> |
    <a class="nav-link" href="{{url_for('toggletheme')}}">Switch Theme</a> |
    <a class="nav-link" href="{{url_for('tos')}}">Terms</a> |
    {% if login_artist %}
    <a class="nav-link" href="{{url_for('create.comic')}}">Upload Comic</a> |
    <a class="nav-link" href="{{url_for('create.series')}}">Create Series</a> |
    {% if login_artist.isadmin %}
    <a class="nav-link" href="{{url_for('admin.admin')}}">Admin panel</a> |
    {% endif %}
    <a class="nav-link" href="{{url_for('auth.logout')}}">Log Out</a>
    {% else %}
    <a class="nav-link" href="{{url_for('auth.create_account')}}">Create Account</a> |
    <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
    {% endif %}
  </div>

  {% for message in get_flashed_messages() %}
  <div class="alert alert-danger">{{ message }}</div>
  {% endfor %}
  {% block content %} {% endblock %}
  </div>
  <div style="position:absolute; bottom: -50px;">
    <p>running version {{VERSION}}, commit ID: {{COMMIT_ID}}</p>
  </div>
</body>

</html>

templates/comic.jinja
{% extends 'base.jinja' %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="All of ComicWorld!" href="/feed" />
{% if series %}
<link rel="alternate" type="application/rss+xml" title="Comics in series: {{series}}" href="{{series}}/feed" />
{% endif %}
<link rel="alternate" type="application/rss+xml" title="{{artist}}'s feed" href="{{artist}}/feed" />
{% endblock %}

{% block content %}
<title>ComicWorld - {{ comic['title'] }}</title>
<div class="center">
    <div class="notecontainer">
        <div class="sticky {{['s1','s2', 's3', 's4']|random}}"
            style="margin-right: auto; width: fit-content; height: fit-content; transform: rotate(0deg);">
            <h2>{% block title %} {{ comic['title'] }} {% endblock %}</h2>
            <span class="badge badge-primary">{{ comic['created'] }}</span>
            <a href="/artists/{{artist}}">
                <span class="badge badge-primary">Created by: {{ artist }}</span>
            </a>
            {% if comic['seriesid'] %}
            <span class="badge badge-primary">From series: <a href="/series/{{series}}">{{ series }}</a></span>
            <br>
            {% endif %}
            <br>
            <img src="/static/comics/{{ comic['id'] }}.{{ comic['fileext'] }}"
                style="object-fit: contain; height: 69vh; width:70w; border-radius: 10px;">
        </div>
    </div>
</div>

<div class="linkbar">
    {% if previouscomic %} <a href="{{ previouscomic }}?via={{ referrer }}">Previous Comic</a>{% endif %}
    {% if previouscomic and nextcomic %}|{% endif %}
    {% if nextcomic %} <a href="{{ nextcomic }}?via={{ referrer }}">Next Comic</a>{% endif %}
</div>
{% endblock %}

templates/create.jinja
{% extends 'base.jinja' %}
{% from 'macros/notepad.jinja' import notepad %}
{% block content %}

{% call notepad("Upload a new comic") %}
<form method="post" enctype=multipart/form-data>
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Post title" class="form-control"
            value="{{ request.form['title'] }}">
    </div>

    <div class="form-group">
        <div class="upload-btn-wrapper">
            <button class="btn">Choose a file</button>
            <br>
            <img id="preview" width="50%" style="padding-top: 5%" />
            <input type="file" id="image" name="image" accept="image/*"
                onchange="document.getElementById('preview').src = window.URL.createObjectURL(this.files[0])">
        </div>
    </div>
    <div class="form-group">
        <label for="series">Series</label>
        <select name="series" id="series" , style="width: 175px">
            <option value="None">No series</option>
            {% for series_name in series %}
            <option value="{{series_name[0]}}">{{series_name[0]}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endcall %}
{% endblock %}

templates/create_account.jinja
{% extends 'base.jinja' %}
{% from 'macros/notepad.jinja' import notepad %}

{% block content %}
{% call notepad("Create Account") %}
<form method="post">
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" class="form-control"
            value="{{ request.form['username'] }}">
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Password" class="form-control">
    </div>

    <div class="form-group">
        <label for="title">signup code</label>
        <input type="text" name="code" placeholder="PlaceYourSignupCodeHere!" class="form-control">
    </div>

    <div class="form-group">
        <label for="ToS">I agree to the <a href="/terms-of-service">Terms of Service</a></label>
        <input type="checkbox" name="ToS" class="form-control" required="">
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endcall %}
{% endblock %}

templates/create_series.jinja
{% extends 'base.jinja' %}
{% from 'macros/notepad.jinja' import notepad %}

{% block content %}
{% call notepad("Create a new series") %}
<form method="post" enctype=multipart/form-data>
    <div class="form-group">
        <label for="name">Series name</label>
        <input type="text" name="name" placeholder="Series Name" class="form-control"
            value="{{ request.form['name'] }}">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endcall %}
{% endblock %}

templates/index.jinja
{% extends 'base.jinja' %}
{% from 'macros/sticky.jinja' import sticky %}
{% from 'macros/notepad.jinja' import notepad %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="All of ComicWorld!" href="/feed" />
{% endblock %}

{% block content %}
{{ notepad("Welcome to ComicWorld", true, page, allownext) }}
<div class="notecontainer">
    {% for comic in comics %}
    {% call sticky(comic['title'], url_for('comics.comic', comic_id=comic['id']), editable=true )%}
    {% if comic['seriesid'] %}
    <span class="badge badge-primary">From series: <a href="/series/{{series[comic['seriesid']]}}">{{
            series[comic['seriesid']] }}</a></span>
    <br>
    {% endif %}
    <span class="badge badge-primary">Created by: <a href="/artists/{{artists[comic['artistid']]}}">{{
            artists[comic['artistid']] }}</a></span>
    <br>
    <span class="badge badge-primary">{{ comic['created'] }}</span>
    <a href="{{ url_for('comics.comic', comic_id=comic['id']) }}">
        <img src="/static/comics/{{ comic['id'] }}.{{ comic['fileext'] }}">
    </a>
    {% endcall %}
    {% endfor %}
    <!-- This fake element is only here to ensure that the final sticky isn't forced to be an extra row down -->
    <div style="visibility:hidden; height:0px; width: 20em"></div>
</div>

<div class="linkbar">
    {% if page - 1 > 0 %} <a href="?page={{page - 1}}">Previous Page</a>{% endif %}{% if page - 1 > 0 and allownext%} |
    {% endif %}{% if allownext %}<a href="?page={{page + 1}}">Next Page</a> {% endif %}
</div>
{% endblock %}

templates/series.jinja
{% extends 'base.jinja' %}
{% from 'macros/sticky.jinja' import sticky %}
{% from 'macros/notepad.jinja' import notepad %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="All of ComicWorld!" href="/feed" />
<link rel="alternate" type="application/rss+xml" title="Comics in series: {{SeriesName}}" href="{{seriesName}}/feed" />
{% endblock %}

{% block content %}
{{ notepad("Series: " + seriesName, navigation=true, page=page, allownext=allownext) }}

<div class="notecontainer">
    {% for comic in comics %}
    {% call sticky(comic['title'], url_for('comics.comic', comic_id=comic['id']), editable=true )%}
    <span class="badge badge-primary">Created by: <a href="/artists/{{artists[comic['artistid']]}}">{{
            artists[comic['artistid']] }}</a></span>
    <br>
    <span class="badge badge-primary">{{ comic['created'] }}</span>
    <a href="{{ url_for('comics.edit', id=comic['id']) }}">
        <span class="badge badge-warning">Edit</span></a>
    <a href="{{ url_for('comics.comic', comic_id=comic['id']) }}">
        <img src="/static/comics/{{ comic['id'] }}.{{ comic['fileext'] }}">
    </a>
    {% endcall %}
    {% endfor %}
    <!-- This fake element is only here to ensure that the final sticky isn't forced to be an extra row down -->
    <div style="visibility:hidden; height:0px; width: 20em"></div>
</div>

<div class="linkbar">
    {% if page - 1 > 0 %} <a href="?page={{page - 1}}">Previous Page</a>{% endif %}{% if page - 1 > 0 and allownext%} |
    {% endif %}{% if allownext %}<a href="?page={{page + 1}}">Next Page</a> {% endif %}
</div>
{% endblock %}